# yaml-language-server: $schema=https://blue-build.org
name: ideapad310-15isk
description: OS per Lenovo IdeaPad con driver Nvidia Legacy 580xx.

# Torniamo all'immagine principale stabile
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  # 1. Pulizia e pacchetti generici
  - type: dnf
    install:
      packages:
        - intel-media-driver 
    remove:
      packages:
        - firefox
        - firefox-langpacks

  # 2. Modulo ufficiale ublue/bluebuild per i driver Nvidia
  - type: akmods
    install:
      - nvidia
    nvidia:
      version: 580 # Specifichiamo la versione corretta per la tua 920MX

  # 3. Parametri del Kernel
  - type: kargs
    kargs:
      - nvidia-drm.modeset=1
      - rd.driver.blacklist=nouveau,nova-core
      - modprobe.blacklist=nouveau,nova-core
      - initcall_blacklist=simpledrm_platform_driver_init

  # 4. Suite Flatpak
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.torproject.torbrowser-launcher
          - org.libreoffice.LibreOffice
          - org.kde.okular
          - org.gnome.Evolution
          - io.missioncenter.MissionCenter
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - org.gnome.Logs
          - org.gnome.Connections
          - org.gnome.baobab
          - com.mattjakeman.ExtensionManager
          - org.gnome.font-viewer
          - org.gnome.TextEditor
          - org.gnome.Boxes
          - org.qbittorrent.qBittorrent
          - com.github.rafostar.Clapper
          - org.gnome.Snapshot
          - org.gnome.Calculator
          - org.gnome.Loupe
          - org.gnome.Contacts
          - org.gnome.Weather
          - org.gnome.clocks
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Maps
