# yaml-language-server: $schema=https://blue-build.org
name: ideapad310-15isk
description: OS per Lenovo IdeaPad con driver Nvidia proprietari estratti via akmods.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: dnf
    install:
      packages:
        - intel-media-driver 
    remove:
      packages:
        - firefox
        - firefox-langpacks

  # Sintassi flat ufficiale del modulo akmods per BlueBuild
  - type: akmods
    install:
      - nvidia
    nvidia-driver: nvidia

  - type: kargs
    kargs:
      - nvidia-drm.modeset=1
      - rd.driver.blacklist=nouveau,nova-core
      - modprobe.blacklist=nouveau,nova-core
      - initcall_blacklist=simpledrm_platform_driver_init

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.torproject.torbrowser-launcher
          - org.libreoffice.LibreOffice
          - org.kde.okular
          - org.gnome.Evolution
          - io.missioncenter.MissionCenter
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - org.gnome.Logs
          - org.gnome.Connections
          - org.gnome.baobab
          - com.mattjakeman.ExtensionManager
          - org.gnome.font-viewer
          - org.gnome.TextEditor
          - org.gnome.Boxes
          - org.qbittorrent.qBittorrent
          - com.github.rafostar.Clapper
          - org.gnome.Snapshot
          - org.gnome.Calculator
          - org.gnome.Loupe
          - org.gnome.Contacts
          - org.gnome.Weather
          - org.gnome.clocks
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Maps
